// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzyeecsyosceacxasxtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6eWVlY3N5b3NjZWFjeGFzeHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTk0NTUsImV4cCI6MjA3NDI5NTQ1NX0.cav1yl_NRxjtSHH7kWbSIfA0h-qXKe72bEG_5HceMpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});